### PR TITLE
Set SMTP via environment vars.

### PR DESCRIPTION
**Pull request by rodrigoaguilera**
Recovered featured from an old PR
https://github.com/nextcloud/docker/pull/292

### CODE REVIEW

**Comment by SnowMB** [comment]
Thanks for continuing the work on this feature. 

Can you add some documentation for that feature to the readme?

**Comment by rodrigoaguilera** [comment]
@SnowMB I added some info the readme. Can you review it?

**Comment by J0WI** [comment]
This needs to be rebased after `16.0` is released.

**Comment by J0WI** [comment]
@rodrigoaguilera `16.0` has been released, would you like to rebase?

**Comment by rodrigoaguilera** [comment]
Done. I just run update.sh

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
