### PR TITLE
WIP: Adding missing dependency for SVG files

### PR DESCRIPTION
**Pull request by LouisVallat**
Possible fix for #1414 with the addition of a missing package.
This only fixes the issue for Debian based images.
Tested with NC21 apache variant.

TODO: alpine variants

### CODE REVIEW

**Comment by J0WI** [comment]
See also https://github.com/nextcloud/docker/pull/1381#issuecomment-785899020

**Comment by LouisVallat** [comment]
> See also [#1381 (comment)](https://github.com/nextcloud/docker/pull/1381#issuecomment-785899020)

Okay so should I close this PR? What could we do about it?
If I understand correctly, including imagick isn't a good idea, but now it's showing a warning in the NC overview page.

**Comment by J0WI** [comment]
https://github.com/nextcloud/docker/issues/594#issuecomment-785891835
> AFAIK the imagemagick binary is only used to convert SVG favicons (using only default configs). Do I miss something?

I don't really understand why Nextcloud displays a warning for this, but I'm glad fore more feedback.

**Comment by LouisVallat** [comment]
image

That's the exact warning that it now shows in NC21. I've never had this warning show up before, and have always been using the `nextcloud:latest` image. This warning is annoying, and the only known way to fix it is to add the package mentioned in issue #1414. I'd love to have an alternative or a way to fix this warning.

**Comment by J0WI** [comment]
Closing due #1414

**Pull request closed without merging**
