### PR TITLE
Set Redis via environment vars

### PR DESCRIPTION
**Pull request by marceljd**
Copy of the Redis part of #292 without the SMTP part. Redis has to be set at boot time, SMTP can be set through the Nextcloud webinterface. Tested with Apache / 14.0.3.

New PR after running update.sh

@rodrigoaguilera @unteem

### CODE REVIEW

**Comment by marceljd** [comment]
#194

**Comment by J0WI** [comment]
I'd also set `memcache.distributed` to redis.
https://docs.nextcloud.com/server/15/admin_manual/configuration_server/caching_configuration.html#recommendations-based-on-type-of-deployment

**Comment by J0WI** [comment]
@marceljd please also add `memcache.distributed`.

**Comment by marceljd** [comment]
@J0WI done, unfortunately I did not have the old sources and did not succeed to commit on this PR. Git opened a new one #599

**Comment by J0WI** [comment]
@marceljd the commits in #599 are quite messy.
Your sources are still available in your [master](https://github.com/marceljd/docker). Can you manage to make your changes there?

**Comment by marceljd** [comment]
@J0WI I tried to update the sources on my linux machine because the fork is already a few months old. After the commit I got an error and had to sign and force-commit, that is why the mess is in 599. Would it be better to delete everything and make the changes to a fresh fork and PR? If I change the sources in my old fork there will be a lot of errors or not?

**Comment by J0WI** [comment]
You can use `git rebase`, but the branch in #599 is completely broken.
Here are some steps you can do:
- Delete the redis branch from #599
- checkout your own `master`
- create a new branch from your master using `git checkout -b branchname`
- checkout your own `master` again
- reset *your* commits from `master` and pull from *our* `master`
- rebase your new `branchname`, apply any updates, run update.sh and push to GitHub
- create a new PR from `branchname`

**Comment by marceljd** [comment]
closed via #600

**Pull request closed without merging**
