### PR TITLE
Read postfix version tags

### PR DESCRIPTION
**Pull request by J0WI**
Restores 'beta', 'alpha' and 'rc' version tags

### CODE REVIEW

**Comment by J0WI** [comment]
@tilosp `nextcloud:beta` and `nextcloud:rc` haven't been updated since https://github.com/nextcloud/docker/commit/b7e9458648f6d8571ff0e3fcf6abf8aadb9dab35. Do we want them again?

**Comment by tilosp** [comment]
I am not sure why I have removed them in the first place.
I see no reason not to have them, but I think your current PR could cause the same tag to be at multiple images. (For example if there are multiple RCs out)

**Comment by J0WI** [comment]
Do we have `alpha` or multiple `beta` releases?

**Comment by tilosp** [comment]
> Do we have `alpha` or multiple `beta` releases?

The were `alpha` releases. For example:  https://github.com/nextcloud/docker/tree/a1ed54243dbcf7e9b7ebdb77fc325a9d8ebdb3a5/16.0-alpha
I don't think that there were ever multiple betas at the same time.

**Pull request closed without merging**
