### PR TITLE
Change sleep time from 3s to 10s in all entrypoint.sh files

### LINKED ISSUE #833: Nextcloud installation fails, when mariadb is not ready: Sleep is too short
The installation of nextcloud (docker-compose with mariadb) sometimes fails, because the database is not ready.

The defaults of sleep (3s) and max_retries (10) in docker-entrypoint.sh are too short for some cases.

Increasing the sleep time to 10s solves the issue for me.

If the database is ready early, it only extends the installation-time a few seconds and if not, it could help others, where the database needs more time.

### PR DESCRIPTION
**Pull request by Nils160988**
Fixes #833, as mentioned there, in some cases the sleep timeout ist too short.

It is my first PR, please be patient and tell me, if my approach is not as desired ;)

### CODE REVIEW

**Comment by J0WI** [comment]
... or should we just change `max_retries`? @tilosp

**Comment by Nils160988** [comment]
Changing max_retries was a solution I also considered. But I thought it will just fill the logs so that increasing sleep timeout is favorable.

**Comment by J0WI** [comment]
On the other hand, an increased timeout will also consume more time if something is wrong.

**Comment by J0WI** [comment]
Related issue: https://github.com/nextcloud/docker/issues/593#issuecomment-573260560
cc @tilosp

**Comment by tilosp** [comment]
:+1: it makes sense to merge this
once the MariaDB bug is fixed we can revert back to 3s

**Comment by J0WI** [comment]
Sorry, I messed up during rebase. Created #963 for it.

**Pull request closed without merging**
