### PR TITLE
Resolves #1124, Resolves #1134: Configure S3 (or compatible) as primary storage through environment variables

### LINKED ISSUE #1124: Autoconfiguration for S3 as Primary Storage
It would be great if S3 Primary Storage could be auto-configured similar to the database or Redis settings. Changing the primary storage in the config file after the installation step leads to some strange effects and prohibits a "serverless" deployment where there is no persistent file system other than S3. All file system extensions i looked up for docker requires root access in the container which are not given for serverless deployment options such as AWS Fargate

### LINKED ISSUE #1134: Configuring S3 (or compatible object storage) as Primary Storage
A way to configure an S3 bucket as primary storage, as per [Configuring Object Storage as Primary Storage](https://docs.nextcloud.com/server/16/admin_manual/configuration_files/primary_storage.html).

I have an example project using the [18-fpm-alpine](https://github.com/nextcloud/docker/tree/master/18.0/fpm-alpine) image source, available [here](https://github.com/nickistre/nextcloud-s3-docker), including a `docker-compose.yml` and Kubernetes files that use [Minio](https://hub.docker.com/r/minio/minio/) as the S3-based back-end. 

Mainly, I'm looking to bring in the [`primary-object-storage.config.php`](https://github.com/nickistre/nextcloud-s3-docker/blob/master/fpm-alpine/config/primary-object-storage.config.php) config file I've created in my test project, update `README.md`, and optionally add an example `docker-compose.yml` that uses Minio. I can do the actual legwork of getting the PR up, but just looking for best development practices here.  Or I can just dive in and make the PR as best I can if that's fine.

### PR DESCRIPTION
**Pull request by nickistre**
#1134

### CODE REVIEW

**Comment by pierreozoux** [comment]
We also have this here:
https://github.com/nextcloud/docker/pull/968/commits/41564649fc3c49de91c4af4a8e36c1ebf0831977

**Comment by pierreozoux** [comment]
@adamjenkins1 yes, feel free :)

**Comment by pierreozoux** [comment]
@nickistre is it fine if we close your PR and use #1124 instead?

**Comment by cuppett** [comment]
> @nickistre is it fine if we close your PR and use #1124 instead?
> 
> @nickistre. and @cuppett if you could review it as well the other PR?
> 
> thanks!

Is there a different PR for it? #1124 is an issue. I've linked this PR to both issues it would resolve.

4156464 has a few deficiencies I wouldn't recommend to merge without cleanups and isn't linked to any issues. Is it part of a PR?

**Comment by nickistre** [comment]
I apologize for my delay on working further on this; just couldn't get the time to get back to this and I had some plans on revamping my own fork and getting the Travis CI build working in it too.

If someone wants to take over, feel free, but hopefully I'll be able to get back started on it this Friday.

**Comment by nickistre** [comment]
> @nickistre is it fine if we close your PR and use #1124 instead?
> 
> @nickistre. and @cuppett if you could review it as well the other PR?
> 
> thanks!

@pierreozoux Do you mean my issue? Do you mean my issue #1135 ?  I'd say closing that is fine as issue #1124 is actually older.  I don't know how I missed it in my searches for this particular problem.

**Comment by cuppett** [comment]
> > @nickistre is it fine if we close your PR and use #1124 instead?
> > @nickistre. and @cuppett if you could review it as well the other PR?
> > thanks!
> 
> @pierreozoux Do you mean closing my issue #1135 ? I'd say closing that is fine as issue #1124 is actually older. I don't know how I missed it in my searches for this particular problem.

Both issues are linked to this PR. If we get this one over the line and they'll both close automatically.

**Comment by pierreozoux** [comment]
Closing in favor of https://github.com/nextcloud/docker/pull/1193

**Pull request closed without merging**
