### PR TITLE
Increase (double) opcache string buffer size

### PR DESCRIPTION
**Pull request by rugk**
This fixes https://github.com/nextcloud/docker/issues/1692
Fixes https://github.com/nextcloud/server/issues/31223

### CODE REVIEW

**Comment by rugk** [comment]
Do I really need that signoff thingy? One cannot do it online with GitHubs UI so I'd need to clone the repo… uff…

**Comment by rugk** [comment]
See also: https://github.com/nextcloud/docker/pull/1703

**Comment by MichaIng** [comment]
Hey guys. What do you think about removing all the other OPcache settings? Those are PHP defaults anyway, with the exception of `opcache.revalidate_freq` which defaults to `2`. This however may be better to set to at least `5` or even higher, Nextcloud AIO uses `60` seconds. This is the amount of seconds after which PHP will revalidate timestamps of cached scripts (hence does disk access) on requests. It is only relevant when `config.php` is edited, defining the maximum time after which the change takes effect. 5 seconds should be sufficiently fast, I think?

**Review by J0WI — CHANGES_REQUESTED** [review]
https://github.com/nextcloud/docker/pull/1702#issuecomment-1046092555

**Comment by J0WI** [comment]
> [#1702 (comment)](https://github.com/nextcloud/docker/pull/1702#issuecomment-1046092555)

I'll fix this in a follow up

**Review by J0WI — APPROVED** [review]

**Pull request merged**
