### PR TITLE
Prevent nginx HTTP Server Detection

### PR DESCRIPTION
**Pull request by t3easy**

### CODE REVIEW

**Comment by J0WI** [comment]
The config is taken from here: https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/nginx-root.conf.sample

**Comment by t3easy** [comment]
> The config is taken from here: https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/nginx-root.conf.sample

@J0WI Should I send a PR to the documentation first?
The setting just hides the nginx version, like

https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/nginx-root.conf.sample#L60

does for the php version.

**Comment by J0WI** [comment]
> Should I send a PR to the documentation first?

Yes please.

**Comment by t3easy** [comment]
> @t3easy any updates? :)

See: https://github.com/nextcloud/documentation/pull/8108

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
