### PR TITLE
Ship 15.0.2 on stable channel

### PR DESCRIPTION
**Pull request by tilosp**
See: https://github.com/nextcloud/updater_server/pull/183

### CODE REVIEW

**Comment by MorrisJobke** [comment]
production should then also be 14.0.6 ;) https://github.com/nextcloud/updater_server/pull/182

**Comment by tilosp** [comment]
@MorrisJobke see: https://github.com/nextcloud/docker/pull/614

**Comment by J0WI** [comment]
I think this could be automated by @tilosp-bot :wink:

**Comment by tilosp** [comment]
@J0WI yes but currently it's really hard, it not easy to get a single version for a channel from this config: https://github.com/nextcloud/updater_server/blob/master/config/config.php
https://github.com/nextcloud/updater_server/issues/68 would solve this.

**Pull request merged**
