### PR TITLE
Simplify first character check in entrypoint.sh

### PR DESCRIPTION
**Pull request by mr700**
Simplify first character check in entrypoint.sh
use "${X:0:1}" instead of ""$(echo "$X" | cut -c1-1)"

Signed-off-by: Doncho N. Gunchev <dgunchev@gmail.com>

### CODE REVIEW

**Comment by nupplaphil** [comment]
@J0WI @mr700 Is this change really working for the `/bin/sh` script?
I had troubles with it, because this syntax is only bash compatible

**Comment by J0WI** [comment]
I've tested it on `busybox sh`.

**Comment by mr700** [comment]
10x @J0WI, `busybox sh` and `busybox ash` support `${X:0:1}`. I was building my own images...

**Comment by nupplaphil** [comment]
OK, I'm sorry that I stressed you, but I took over this part of code for my Docker image and ran into the regression 
`/entrypoint.sh: 52: Bad substitution`
(see https://github.com/friendica/docker/issues/196 )
and the test-case to reproduce it was:
```console
docker run --rm -it --entrypoint="/bin/sh" php:7.4-apache-bullseye
# export REDIS_HOST=friendica-redis.friendica.svc.cluster.local
# echo ${REDIS_HOST:0:1}
/bin/sh: 2: Bad substitution
```

**Comment by kemoantemo** [comment]
@nupplaphil I built the apache version myself and when I try to use Redis it gives me error
image
and without redis it works normally
don't know if the problem is with me building wrong the only thing i did is clone the repo and cd to
`/docker/23/apache`
then
`docker build -t nextcloud:23.0.2 .`
and used this image
the problem not there with the official 23.0.1 image

**Pull request merged**
