### PR TITLE
Set Redis via environment variables

### PR DESCRIPTION
**Pull request by marceljd**
Copy of the Redis part of #292 without the SMTP part. Redis has to be set at boot time, SMTP can be set through the Nextcloud webinterface. Tested with Apache / 14.0.3.

@rodrigoaguilera @unteem

### CODE REVIEW

**Comment by marceljd** [comment]
Did the test fail because of trying to change a file that was not merged / approved yet? I changed the readme.md and updated later with a link to the Redis official repository.

**Comment by rodrigoaguilera** [comment]
If I remember right you need to run update.sh to modify the images for all the version variants

**Comment by SnowMB** [comment]
@rodrigoaguilera is right. You have to run `./update.sh` so that all the images get updated.

**Comment by marceljd** [comment]
How do I run ./update.sh? Download the entire repository into linux and run it, then upload everything again? Or is there a better / quicker way? Sorry I have to ask, I could not find out how to do this...

**Pull request closed without merging**
