### PR TITLE
Update stable to 20.0.7

### PR DESCRIPTION
**Pull request by Crocmagnon**
Do I need to do something else to generate 20.0.7 images and push them to docker hub ? If no, is there some place I can check the progress ? :)

### CODE REVIEW

**Comment by LedzZm** [comment]
I guess it needs to pass the tests, also waiting for that myself.

**Comment by Crocmagnon** [comment]
I fixed the DCO check, but for the other failing I don't know what to do 😕

**Comment by LedzZm** [comment]
I tried to pr a signed commit as well before this started running and still got same (and additional) errors. 

Could it be that there is some more general issue with the version or that we should run some update script?

**Comment by nshtg** [comment]
Why is nextcloud incapable of pushing their newest releases to official docker in a timely manner? Almost 3 days have passed ?!

**Comment by Crocmagnon** [comment]
Yeah that’s why I searched for how to do this here 😕
It’s like they don’t care about delivering their versions to docker users 😕

**Comment by b3nis** [comment]
Relax. I am sure they care - but it might take a few days.

**Comment by Crocmagnon** [comment]
Haha sorry for the harsh tone ☺️ I'm relaxed! English is not my main language.

I'll try to rephrase: It makes me feel like docker is a second-class citizen in the landscape of Nextcloud deployments methods.

**Comment by b3nis** [comment]
> Haha sorry for the harsh tone relaxed I'm relaxed! English is not my main language.
> 
> I'll try to rephrase: It makes me feel like docker is a second-class citizen in the landscape of Nextcloud deployments methods.

Maybe it is :-) I dunno what is the most common "way" of hosting NC in general, but maybe not Docker? I mean, I can understand if Nextcloud is focusing on the platform used by their enterprise customers.

**Comment by nshtg** [comment]
> Maybe it is :-) I dunno what is the most common "way" of hosting NC in general, but maybe not Docker? I mean, I can understand if Nextcloud is focusing on the platform used by their enterprise customers.

Far more than 10M+ pulls imply a huge amount of instances using docker.

And "focusing" on their enterprise customers may be the case, but in my opinion that is no excuse to not keep their docker images up to date in a timely manner - updating it literally costs **less than 5 minutes** !!!

**Comment by Crocmagnon** [comment]
> updating it literally costs less than 5 minutes

It could (should?) even be automated and cost nothing :)

**Comment by RomainTT** [comment]
What I don’t get is that errors come from other versions, not 20.0.7. And still it blocks the PR.

**Comment by LedzZm** [comment]
Is it possible to rerun the deployment? 

The errors that appeared on the two consecutive runs were very inconsistent and the builds had an 1 day gap, with no actual changes in the codebase i believe. 

So maybe i was thinking there might have been an issue with the pipeline.

**Comment by ChristophWurst** [comment]
> I'll try to rephrase: It makes me feel like docker is a second-class citizen in the landscape of Nextcloud deployments methods.

FWIW it has shown to work most reliably, hence https://docs.nextcloud.com/server/latest/admin_manual/installation/source_installation.html describes a classic LAMP setup.

While I agree that a delay on this deployment method is very unfortunate I don't see in which why the server team is blocking this? What's different to the 20.0.6? The change set is minimal: https://nextcloud.com/changelog/#latest20.

**Comment by ChristophWurst** [comment]
I've restarted the checks. Let's see :v:

**Comment by LedzZm** [comment]
The nextcloud-cli-mysql service seems to be the issue. And I see it failing on tests performed for other, older versions, unless i misunderstand something.

**Comment by lenke182** [comment]
Someone could add more debug statements to the test scripts.

The relevant test scripts contains `$RANDOM` and `$$` as code, which both behave explicitly or implicitly random. These influence the database name, username and password as well as the Nextcloud admin username and password. Could this be the reason for the inconsistent results?

[1] https://github.com/docker-library/official-images/blob/master/test/tests/nextcloud-cli-mysql/run.sh
[2] https://github.com/docker-library/official-images/blob/master/test/tests/nextcloud-cli-postgres/run.sh

**Comment by J0WI** [comment]
Sorry for the delay, I'll take care in a minute.

The issue with the stable tag and why it's not automated is mentioned here: https://github.com/nextcloud/updater_server/issues/68. TL;DR we can easily monitor and automate releases and tags, but not channels like stable or production.
For the test failures https://github.com/nextcloud/server/pull/16708 has been opened, but there seems to be another race condition in `occ maintenance:install`. Any help to debug the failures is highly appreciated.

**Review by J0WI — APPROVED** [review]

**Comment by nRaecheR** [comment]
While the 20.0.7-* tags are online now, the 20 tag is still missing on docker hub.

**Comment by nijel** [comment]
It seems that amd64 images are actually missing...

**Comment by marliyev** [comment]
20.0.7 still missing, tried just now

**Comment by nRaecheR** [comment]
It's there but not for the AMD64 arch it seems.

**Comment by marliyev** [comment]
yep, tag there but image missing :)

**Pull request merged**
