### PR TITLE
[chore] dev env dockerfile draft

### PR DESCRIPTION
**Pull request by m4dz**
Hey Nexclouders!

for quick start development, I've made a `Dockerfile` to build a development docker environment. It's a first draft, based on the `apache` version that I rewrote a little bit. I now need your inputs to find how we can improve it :smiley:. So I have few questions:

1. yet, it excludes some PHP modules like
  - `smbclient`, `ftp` and `imap`
  - `gmp`
  - `memcached` and `redis`
  - `imagick` and the preview deps tools (`ffmpeg`, `avconv`, `LibreOffice`)
should we consider, as the image if for development purposes, that we need to provide them, or is it too much?

2. It actually uses a `sqlite` db for storage, which is fine for development I guess, but once again, if this image is used for development, we maybe need to also embed a MariaDB and a PgSQL, or at least give a simple way to compose a docker image with those DB, isn't it?

3. I see that the dockerfiles are generated from templates. I so could contribute to them for the `nextcloud:dev` dockerfile so I can be generated as well. Do it sounds good?

4. We can actually run it with `cd nextcloud/server && docker --rm -it -p 8080:80 -v $(pwd):/var/www/html nextcloud:dev`, but even if my proposal is a little bit different than the `apache` version, maybe the latter is sufficient for dev purposes, so this PR isn't really relevant. Any thoughts about it?

Thanks for your opinions!

### CODE REVIEW

**Comment by SnowMB** [comment]
In my opinion a dev docker file belongs directly to the server repo. There was a pull request a while ago, but no reaction to change requests so it's still open. See https://github.com/nextcloud/server/pull/4355.

> It actually uses a sqlite db for storage, which is fine for development I guess, but once again, if this image is used for development, we maybe need to also embed a MariaDB and a PgSQL, or at least give a simple way to compose a docker image with those DB, isn't it?

Just run a plain database container. What's the problem with it? It's documented in the examples.

**Comment by m4dz** [comment]
Thanks @SnowMB! Fine for running a plain database container, seems legit, just wanna ask for any opinions, but it's also my favorite choice. About hosting the Dockerfile in the `server` repo, I'm not sure: IMHO nextcloud can provide an already built image at `nextcloud:dev` as it provides a `nexcloud:fpm` image. I don't think any developer have to build its own dev image, nope?

**Comment by tilosp** [comment]
I don't think that the dev image should be part of the official docker repo. Images on there should be "generally useful" and i don't think that the dev image is "generally useful". 

If you want to provide a prebuild image we could publish it to a docker hub organization.

**Comment by cosenal** [comment]
@m4dz I would encourage you to contribute to my PR instead, https://github.com/nextcloud/server/pull/4355

If you see the comments there, there is an agreement that a Docker setup belongs to the main repo.

**Pull request closed without merging**
