### PR TITLE
Alpine Linux image with fpm and php7.0

### PR DESCRIPTION
**Pull request by eniac111**
Hello,

I've divided the images in different directories and inserted the Travis tests from the official Docker images, they are passing.
The only difference between the images is that there is still no Memcache support in php-fpm 7.0.

https://travis-ci.org/eniac111/nextcloud-docker/branches

### CODE REVIEW

**Comment by SnowMB** [comment]
Awesome work! +1

**Comment by pierreozoux** [comment]
Ok, we got merged \o/ the image is now official!

So various remarks before merging this one :)
Could you put your PR on top of #21 please?
And one PR for travis and one for Alpine would be amazing (or just 2 commits in this PR would be fine also).

Thanks again!

**Comment by eniac111** [comment]
Hello @pierreozoux  and congrats :) 
I moved my Alpine images to separate version directories like in #21 but the official NextCloud image is still in "php5.6" directory. I'm not sure what to do with it. It may cause a conflict? Should I move it to "10.0/fpm"?

About Travis, I may move it to another branch and create a separate pull request for it?

**Comment by pierreozoux** [comment]
Sorry for the delay, I just merge the PR to reorganize by folder.
If you can rebase and PR on top, would be fine.
Let's use the "alpine" dir and tag.

**Comment by pierreozoux** [comment]
Arf, and also, can you answer there also?
https://github.com/nextcloud/docker/issues/10

We need to be coherent, so either all php7 or not if you see what I mean.

**Comment by eniac111** [comment]
Hello @pierreozoux,

I'm not sure how to deal with the conflicts. It would be easier if I create a new, fresh clone of the repository, commit the latest changes and create PRs for the Alpine image and Travis?

**Comment by pierreozoux** [comment]
Yes please do so :)

And the best would be to also use update.sh!

Let me know if you need help!

**Pull request closed without merging**
