### PR TITLE
Make php.ini variable memory_limit configurable via environment variable

### PR DESCRIPTION
**Pull request by xxorde**
I was running in the problem that my Nextcloud instance runs out of memory when uploading to much media from my phone due to a quite tight memory limit.

I would have assumed that that such an important setting can be easily changed via an environment variable.
But unfortunately the configuration is set by the Dockerfile during build and a custom configuration file needs to be put into the container.

With my purposed change a potential custom configuration file is not changed.
If no custom `memory-limit.ini`  was deployed the container will use the environment variable `PHP_INI_MEMORY_LIMIT` or set a reasonable small default of `1024M`.

### CODE REVIEW

**Comment by xxorde** [comment]
When I run `update.sh` quite some variables are updated like `17.0.9RC2`, and many builds / checks fail.
When I manually remove the updated tags I get the failed check `update.sh / Check for Changes ` because I obviously did not applied all changes.

Many of the builds still fail so I will reapply the update script an push again.

**Comment by kesselb** [comment]
Thanks for your pull request 👍

I would change the default 512M to 1024M. The option to change it via env looks unnecessary to me.

**Comment by J0WI** [comment]
We just follow upstream recommendation

https://github.com/nextcloud/server/blob/b9287f9780c6743f0f5e2db84fe32c470cf70b22/lib/private/MemoryInfo.php#L34

**Comment by kesselb** [comment]
I don't see a upstream issue. This pull request is about an option to overwrite the memory limit without recompiling the image. A warning is shown if the memory_limit is less than 512mb. A memory_limit above 512mb does not trigger a warning. I guess for some people 512mb works, for most people 1024mb should work and sometimes even 2048mb are necessary. 

@xxorde mind to rebase your branch and change the default back to 512mb?

**Comment by J0WI** [comment]
> I don't see a upstream issue. This pull request is about an option to overwrite the memory limit without recompiling the image. 

I mean changing the default to 1024M should be discussed upstream.

https://github.com/docker-library/official-images/pull/9426#issuecomment-760553422 suggest to embed this directly in the generated php.ini. I guess we can do the same in #865.

@xxorde it's fine to change only the templates to avoid merge conflicts. GitHub Workflow will apply them after merge.

**Comment by kesselb** [comment]
> @xxorde it's fine to change only the templates to avoid merge conflicts. GitHub Workflow will apply them after merge.

@xxorde he is asking you to change  Dockerfile-alpine.template, Dockerfile-debian.template, README.md and docker-entrypoint.sh. And leave the other files unchanged. A bot will use the above files to create the other files.

**Comment by J0WI** [comment]
I'm also considering implementing [this proposal](https://github.com/docker-library/official-images/pull/9426#issuecomment-760553422) to fix this and #865.

**Comment by xxorde** [comment]
> @xxorde he is asking you to change Dockerfile-alpine.template, Dockerfile-debian.template, README.md and docker-entrypoint.sh. And leave the other files unchanged. A bot will use the above files to create the other files.

@kesselb Ah, thanks. This PR is a bit old and I had in mind I need to check in the results of update.sh in order to not trigger an error in the build pipeline.

**Comment by xxorde** [comment]
I do not get how I am able to change the sign-off on auto generated commits coming from "Github Workflow".

Bildschirmfoto vom 2021-01-22 16-33-20

If this PR creates to much work, please feel free to just close it.

**Comment by kesselb** [comment]
> I do not get how I am able to change the sign-off on auto generated commits coming from "Github Workflow".

It's important that your commits are signed off. I think it's fine to ignore the commits by Github Workflow.

> This branch has conflicts that must be resolved

Would you mind to rebase your branch with the latest master? If you are not familiar with rebasing you may checkout master again and recreate the changes. Thanks :+1:

**Comment by J0WI** [comment]
> I'm also considering implementing [this proposal](https://github.com/docker-library/official-images/pull/9426#issuecomment-760553422) to fix this and #865.

I just submitted #1379 for this

**Comment by kesselb** [comment]
Thanks @xxorde for your pull request :+1: 

I'm closing it in favour of #1379.

**Pull request closed without merging**
