### PR TITLE
Starting cron without new docker-container

### PR DESCRIPTION
**Pull request by AndreKoepke**
Nextxloud should maintain the cron-service without multiple docker-containers which mounts the same directory.

See this issue as reference: https://github.com/nextcloud/docker/issues/627

### CODE REVIEW

**Comment by AndreKoepke** [comment]
I'm not sure why the checks failed. I assumed that I not changed anything for older versions and why their postgres got trouble.

**Comment by J0WI** [comment]
You can simply use the `--entrypoint` flag: https://github.com/nextcloud/docker/blob/d1d4467e34df2b1d39c75f02c9b1f7e6f872d76a/.examples/docker-compose/insecure/mariadb-cron-redis/apache/docker-compose.yml#L35-L40

**Comment by AndreKoepke** [comment]
@J0WI sadly not. I had to start two containers (both with the same mount point).
But one container is enough.

Iam using nextcloud in a kubernetes environment. And I don't want to start an additional container only for cron.

**Comment by J0WI** [comment]
Then you should look for https://github.com/nextcloud/docker/tree/master/.examples/dockerfiles/cron

**Comment by AndreKoepke** [comment]
Thanks, but there is the same problem: I have to start a second container with the same mount point. 

And the second container needs a whole PHP environment.

That's the reason why I want to run the cron-job parallel in the same container. ^^

**Comment by AndreKoepke** [comment]
Ah, my bad.

Nice, that's exactly what I am looking for.

**Pull request closed without merging**
