### PR TITLE
Alpine 3.13

### LINKED ISSUE #1299: iconv does not work properly on fpm-alpine
There currently seems to be an issue with iconv on alpine linux which means that specific plugins and other NC functionalities break if iconv is needed. This happens for example with the mail app and is noted in this issue: https://github.com/nextcloud/mail/issues/3999

There seems to be apossible workaround as linked to the corresponding StackOverflow link: https://stackoverflow.com/questions/63746822/why-does-iconv-returns-empty-string-in-php7-4-fpm-alpine-docker/63747282#63747282
However I'm not sure if this is desirable to be implemented in this Dockerfile

### PR DESCRIPTION
**Pull request by J0WI**
Closes #1299 #1300

### CODE REVIEW

**Comment by AlterDepp** [comment]
Perhaps this fixes https://github.com/nextcloud/mail/issues/4351 (nextcloud mail broken)

**Comment by J0WI** [comment]
Yes it will once [this](https://github.com/docker-library/official-images/blob/master/library/nextcloud) is updated.

**Comment by snevas** [comment]
> Perhaps this fixes [nextcloud/mail#4351](https://github.com/nextcloud/mail/issues/4351) (nextcloud mail broken)

I tested today, and sadly it doesn't.

**Comment by AlterDepp** [comment]
> > Perhaps this fixes [nextcloud/mail#4351](https://github.com/nextcloud/mail/issues/4351) (nextcloud mail broken)
> 
> I tested today, and sadly it doesn't.

same for me. Tested with dockerhub:nextloud 20.0.7-fpm-alpine with php:7.4-fpm-alpine3.13

**Comment by AlterDepp** [comment]
Fixed for me with nextcloud 20.0.8-fpm-alpine and mail app 1.9.1
Thanks

**Pull request merged**
